Themes/Bong.Default/Components/NavbarViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Bong.Default.Components
{
    public class NavbarViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult<IViewComponentResult>(View("Navbar"));
        }
    }
}

Themes/Bong.Default/Views/Index.cshtml
@section scripts
{}

@{
    ViewBag.Title = "Hello from Bong!";
    Layout = "_Layout";
}

<vc:posts></vc:posts>

Themes/Bong.Default/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="apple-touch-icon" href="icon.png">

    <link rel="stylesheet" type="text/css" href="~/Themes/Bong.Default/Styles/spectre.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Themes/Bong.Default/styles/spectre-exp.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Themes/Bong.Default/styles/spectre-icons.min.css" />

    <link rel="stylesheet" type="text/css" href="~/Themes/Bong.Default/styles/default.min.css" />

    @RenderSection("styles", false)
</head>

<body>
    <!--[if lte IE 9]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->
    <div class="container parent">
        <div class="columns col-gapless">
            <div class="column col-1 sidebar">
                <vc:navbar></vc:navbar>
            </div>
            <div class="column col-11 content">
                @RenderBody()
            </div>
        </div>
    </div>

    @RenderSection("scripts", false)
</body>
</html>